from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1031, 551)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1011, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plusRowButon = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.plusRowButon.setObjectName("plusRowButon")
        self.horizontalLayout.addWidget(self.plusRowButon)
        self.plusColButon = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.plusColButon.setObjectName("plusColButon")
        self.horizontalLayout.addWidget(self.plusColButon)
        self.clearBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clearBut.setAutoFillBackground(False)
        self.clearBut.setAutoDefault(False)
        self.clearBut.setDefault(False)
        self.clearBut.setFlat(False)
        self.clearBut.setObjectName("clearBut")
        self.horizontalLayout.addWidget(self.clearBut)
        self.deleteBut = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deleteBut.setObjectName("deleteBut")
        self.horizontalLayout.addWidget(self.deleteBut)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.mainTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.mainTable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.mainTable.setObjectName("mainTable")
        self.mainTable.setColumnCount(0)
        self.mainTable.setRowCount(0)
        self.verticalLayout.addWidget(self.mainTable)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1031, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Создание таблицы"))
        self.plusRowButon.setText(_translate("MainWindow", "Добавить строку"))
        self.plusColButon.setText(_translate("MainWindow", "Добавить стобец"))
        self.clearBut.setText(_translate("MainWindow", "Очистить"))
        self.deleteBut.setText(_translate("MainWindow", "Удалить"))
        self.menu.setTitle(_translate("MainWindow", "Таблица"))
        self.action.setText(_translate("MainWindow", "Сохранить"))
